### ISSUE TITLE
Example for using the HA-Garage-Door

### ISSUE THREAD

**Issue by dacorn** [bphillips09/Control4-HA-Garage-Door#1]
I tried to add the driver to an existing cover from Home Assistant but I wasn't sure if I need to add any connections or exactly how this should work. I added the entity to the driver but it doesn't show up in C4.

In connections only Shelly devices show up in the Top and bottom button link in the connections view. I do have some shellys I use but more are the Sonoff Dual R3 devices as the Shelly 2PM have not been very durable.

**Comment by bphillips09** [comment]
@dacorn Were you able to get this set up correctly?

**Comment by bphillips09** [comment]
Assuming this has been resolved.
